name: CI

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: arunvelsriram/utils:latest

      - name: Install bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Test
        run: |
          docker images

      - name: Run test
        run: bats test/test.bats
